version: "3.2"

services:
  postgres:
    image: postgres
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alianca_intercab
    ports:
      - "3306:3306"
    command: -p 3306
    networks:
      - postgres-compose-netwrok
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - CLUSTERED=true

networks:
  rabbitmq_go_net:
    driver: bridge
  postgres-compose-netwrok:
    driver: bridge
